Update README.md
coala-analyzer/coala-gedit pull request #23
Opened 2017-11-21 21:20 UTC by lwindolf

Hi!

I like the plugins people write for Gedit, like yours!

And I also am very frustrated with 3rd party plugin finding and installation in Gedit and wrote a plugin to simplify it. It is not perfect as it is AFAIK not possible to safely activate the plugin after installing, but I hope this can be solved in the future.

For now please consider this PR as a suggestion to propagate an easier 3rd party plugin installation.

Note that gedit-plugininstaller does several things:

- download + installation from github
- checking for pip3
- check + installation of Python modules
- enabling the plugin
- reminding the user about restarting gedit

I'd be happy about any feedback!

With Best Regards,
Lars

2017-12-19 12:30 UTC, IpshitaC reviewed
Hi!
I wonder if you could consider opening an issue for this [here](https://github.com/coala/coala-gedit/issues) and then linking this PR to the issue? 
Also, feel free to ping the community on [Gitter](https://gitter.im/coala/coala) and we'll be happy to discuss this 😄

2018-04-18 19:50 UTC, jayvdb commented
blocked on moban

2018-05-02 18:30 UTC, lwindolf commented
@IpshitaC Sorry that it took me so long. As suggested I added a issue for this PR

2018-05-03 00:25 UTC, jayvdb requested changes
@lwindolf , would you be so kind to update your commit message to follow http://coala.io/commit

```
README.md: Mention gedit-plugininstaller

Closes https://github.com/coala/coala-gedit/issues/26
```

2018-05-03 00:25 UTC, jayvdb commented on README.md
> +For easy automatic installation you can install this plugin using the [Gedit Plugin Installer](https://github.com/lwindolf/gedit-plugininstaller/) or you can do it manually:
" or you can do it manually:" .. "For manual installation run" is a bit repetitive.

IMO just remove " or you can do it manually:"

2018-05-03 00:25 UTC, jayvdb commented on README.md
> +For easy automatic installation you can install this plugin using the [Gedit Plugin Installer](https://github.com/lwindolf/gedit-plugininstaller/) or you can do it manually:
Also break the lines to be <= 80cpl.

2018-05-03 00:25 UTC, jayvdb commented on README.md
> +to copy the files into the right places. Feel free to submit a Pull Request featuring a cleaner way!
put the second sentence on a new line.

2022-06-21 20:18 UTC, lwindolf commented on README.md
> +For easy automatic installation you can install this plugin using the [Gedit Plugin Installer](https://github.com/lwindolf/gedit-plugininstaller/) or you can do it manually:
Done. Although 80cpl is not fully possibly with Markdown link.

2022-06-21 20:18 UTC, lwindolf commented on README.md
> +to copy the files into the right places. Feel free to submit a Pull Request featuring a cleaner way!
Done.

2022-06-21 20:24 UTC, lwindolf commented
Commit message also adapted.

2023-05-06 16:21 UTC, closed without merging